#!/bin/bash

WALLPAPER_DIR="/home/$USER/Stuff/Pictures/Wallpapers"

SELECTED=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \) | while read -r wallpaper; do
    filename=$(basename "$wallpaper")
    printf "%s\0icon\x1f%s\n" "$filename" "$wallpaper"
done | rofi -dmenu -p "Wallpaper" -show-icons)

if [ -n "$SELECTED" ]; then
    WALLPAPER_PATH=$(find "$WALLPAPER_DIR" -type f -name "$SELECTED" | head -n1)
    
    if [ -n "$WALLPAPER_PATH" ]; then
        matugen image --show-colors "$WALLPAPER_PATH" -m "dark";
    fi
fi
