"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[palette]
os = "#FFFFFF"
pink = "#F5BDE6"
lavender = "#B7BDF8"
blue = "#8AADF4"
white = "#FFFFFF"
text = "#000000"

[transient_prompt]
background = "transparent"
foreground = "white"
template = " ❯"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "#2d2d2d"
  foreground = "#5cceff"
  style = "diamond"
  trailing_diamond = ""
  template = " {{.Icon}} "
  type = "os"

  [[blocks.segments]]
  background = "#5cceff"
  foreground = "p:text"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  template = " {{ .UserName }} "
  type = "session"

  [[blocks.segments]]
  background = "#cc8323"
  foreground = "p:text"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  template = " {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    folder_icon = "  "
    folder_separator_icon = "\ue0b1"
    home_icon = "󰋜 "
    style = "agnoster_short"

  [[blocks.segments]]
  background = "p:lavender"
  foreground = "p:text"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  template = "  {{ .HEAD }}"
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = false
    fetch_upstream_icon = false
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "
