#!/bin/bash

WALLPAPER_DIR="/home/$USER/Dotfiles/Wallpapers"

SELECTED=$(find "$WALLPAPER_DIR" -type f | while read -r wallpaper; do
    filename=$(basename "$wallpaper")
    printf "%s\0icon\x1f%s\n" "$filename" "$wallpaper"

done | rofi -dmenu -p "Wallpaper" -show-icons)

WALLPAPER_PATH=$(find "$WALLPAPER_DIR" -type f -name "$SELECTED" | head -n1)

if [[ -n "$WALLPAPER_PATH" ]]; then
    if [[ "$SELECTED" == *L.png ]]; then
        matugen image --show-colors "$WALLPAPER_PATH" -m light
    else
        matugen image --show-colors "$WALLPAPER_PATH" -m dark
    fi
fi
